### ISSUE TITLE
robots.txt blocking Google from indexing the paterns.innersourcecommons.org 

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.org#101]
**Describe the bug**
Google has indexed the new website however it came back with the warning that robots.txt blocked https://patterns.innersourcecommons.org/

**Expected behavior**
https://patterns.innersourcecommons.org/ should be indexable by Google.

**Additional context**
Please remove the following from robots.txt file: https://patterns.innersourcecommons.org/robots.txt 

User-agent: *
Disallow: /

**Comment by spier** [comment]
To generate the content for patterns.innersourcecommons.org we use a service called gitbook.com.

The [robots.txt](https://patterns.innersourcecommons.org/robots.txt) mentioned above must be generated by gitbook, because we did not create that file ourselves.

However I just found one configuration setting on gitbook that sounds related:
* **Unlisted** - The content will only be visible to those with the link. It won’t be indexed on Google.

This **Unlisted** setting was enabled, probably from the time when we were still preparing for the release of the book.

I have disabled this setting now, and hopefully that will allow all content to be indexed.

I just checked, and the [robots.txt](https://patterns.innersourcecommons.org/robots.txt) now contains:
```
User-agent: *
Allow: /
```

That sounds more promising, right? :)

**Comment by clcoffey** [comment]
That's great! Thanks Sebastian! I will let you know if this fixed it as soon as Google finishes the verification.

**Comment by clcoffey** [comment]
Sorry Sebastian but it seems like your fix hasn't worked. :-(

![screencapture-search-google-search-console-index-drilldown-2021-03-27-21_24_45](https://user-images.githubusercontent.com/78749459/112735398-975d7f80-8f43-11eb-8e40-0f0a16ce0878.png)

**Comment by spier** [comment]
That's strange. 

What do you see when you click that "See Details" button in the Search Console?

Also some of the patterns have been indexed by Google apparently. 
Not sure how that would work if the `robots.txt` would really generally forbid it?
See https://www.google.com/search?q=site:patterns.innersourcecommons.org

**Comment by clcoffey** [comment]
Hi @spier 
Sorry for the late reply. There isn't much more information when I click on "See Details". Please find below the screenshot. 
I can try and ask them to validate it again and see if we get the same problem. It seems like it's the only page they are having trouble with. Also, they are coming back with a working rather than an error so maybe it's not that bad. 

![screencapture-search-google-search-console-index-validation-2021-04-01-12_29_25](https://user-images.githubusercontent.com/78749459/113288056-57512080-92e6-11eb-8002-9cdcfb08fa2c.png)

**Comment by spier** [comment]
@clcoffey last time I checked google had indexed 8 pages already. Not its up to 20 indexed pages.
I believe the total page count in the book is 24 or so, so the indexing is almost done.

As for the strange behavior in the Google Search Console: I really don't know.

So maybe just try to validate again, as you were saying?

**Comment by clcoffey** [comment]
This worked. Thanks @spier.
Closing this issue now.
